---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-exam-api-service
spec:
  selector:
    app:  {{.Release.Name}}-exam-api-service
  type:  NodePort
  ports:
  - name:  http
    port:  8084
    targetPort:  8084
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-patient-api-service
spec:
  selector:
    app:  {{.Release.Name}}-patient-api-service
  type:  NodePort
  ports:
  - name:  http
    port:  8083
    targetPort:  8083
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-react-app-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: {{.Release.Name}}-react-app-service
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-security-api-service
spec:
  selector:
    app:  {{.Release.Name}}-security-api-service
  type:  NodePort
  ports:
  - name:  http
    port:  8081
    targetPort:  8081
---
kind: Service
apiVersion: v1
metadata:
  name: {{.Release.Name}}-surgery-api-service
spec:
  selector:
    app:  {{.Release.Name}}-surgery-api-service
  type:  NodePort
  ports:
  - name:  http
    port:  8082
    targetPort:  8082
---