apiVersion: apps/v1
kind: Deployment
metadata:
  name: Exam API
  labels:
    app: exam-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exam-api
  template:
    metadata:
      labels:
        app: exam-api
    spec:
      containers:
      - name: exam-api
        image: Enter containers image