apiVersion: apps/v1
kind: Deployment
metadata:
  name: Patient API
  labels:
    app: patient-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-api
  template:
    metadata:
      labels:
        app: patient-api
    spec:
      containers:
      - name: patient-api
        image: Enter containers image