apiVersion: apps/v1
kind: Deployment
metadata:
  name: Surgery API
  labels:
    app: surgery-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surgery-api
  template:
    metadata:
      labels:
        app: surgery-api
    spec:
      containers:
      - name: surgery-api
        image: Enter containers image